"""
Reflection Engine for R&D Simulation Agents.
Enables agents to periodically reflect on their experiences,
generate higher-level insights, and form meta-cognitive awareness.
Inspired by Stanford Generative Agents' reflection mechanism.
"""

from typing import Optional


# Reflection threshold — cumulative importance score that triggers reflection
REFLECTION_THRESHOLD = 25


class ReflectionEngine:
    """
    Manages the reflection process for agents.
    Reflections are generated by the LLM and stored back into memory.
    """

    def __init__(self, importance_threshold: int = REFLECTION_THRESHOLD):
        self.importance_threshold = importance_threshold
        self.last_reflection_round: dict[str, int] = {}  # agent_id -> last round reflected

    def should_reflect(self, agent_id: str, memory_stream, current_round: int) -> bool:
        """
        Determine if an agent should reflect based on:
        1. Cumulative importance of recent memories exceeding threshold
        2. Not having reflected in the current round yet
        """
        last_round = self.last_reflection_round.get(agent_id, -1)
        if last_round >= current_round:
            return False  # Already reflected this round

        since_round = max(last_round, 0)
        cumulative = memory_stream.get_cumulative_importance(since_round=since_round)
        return cumulative >= self.importance_threshold

    def build_reflection_prompt(self, agent_name: str, agent_role: str, recent_memories: list) -> str:
        """
        Build the prompt that asks the agent to reflect on recent experiences.
        Returns the prompt string to send to the LLM.
        """
        memory_text = ""
        for mem in recent_memories:
            memory_text += f"  - [{mem.memory_type}] {mem.content}\n"

        prompt = f"""You are {agent_name} ({agent_role}). 

Based on your recent experiences and observations, please reflect deeply and provide:

1. **Salient Questions** (2-3 key questions that arise from your recent work):
   - What are the most important open questions?
   - What assumptions should be challenged?

2. **Insights** (2-3 higher-level realizations or connections):
   - What patterns do you see across different pieces of information?
   - How do the contributions from different colleagues connect or conflict?
   - What is the most important thing you've learned?

3. **Self-Assessment**:
   - What went well in your recent work?
   - What could you improve or approach differently?
   - Rate your confidence in your conclusions (high/medium/low)

YOUR RECENT EXPERIENCES:
{memory_text}

Respond in a structured format with clear headers for each section. Be genuine to your personality and role. Think deeply — don't just summarize, synthesize."""

        return prompt

    def build_synthesis_prompt(
        self,
        agent_name: str,
        agent_role: str,
        team_reflections: list[dict],
        own_reflection: str,
    ) -> str:
        """
        Build a prompt for higher-level synthesis — used by leads and VP.
        Takes in reflections from team members and produces meta-insights.
        """
        team_text = ""
        for ref in team_reflections:
            team_text += f"\n--- {ref['agent_name']} ({ref['agent_role']}) ---\n"
            team_text += ref.get('reflection_content', ref.get('reflection', '')) + "\n"

        prompt = f"""You are {agent_name} ({agent_role}).

Your team members have shared their reflections. Combined with your own thinking, perform a HIGHER-LEVEL SYNTHESIS:

YOUR OWN REFLECTION:
{own_reflection}

TEAM REFLECTIONS:
{team_text}

Please provide:

1. **Cross-Cutting Themes**: What patterns emerge across the team's thinking?

2. **Alignment & Conflicts**: Where does the team agree? Where are there tensions or disagreements that need resolution?

3. **Strategic Insights**: What higher-level conclusions can you draw that no single team member could see on their own?

4. **Recommendations**: Based on this synthesis, what should the team focus on next?

5. **Risk Assessment**: What risks or blind spots has the team collectively missed?

Be thoughtful, strategic, and true to your leadership style. Synthesize — don't just aggregate."""

        return prompt

    def parse_reflection_output(self, output: str) -> dict:
        """
        Parse the reflection output into structured components.
        Returns a dict with salient_questions, insights, self_assessment.
        """
        return {
            "raw_content": output,
            "parsed": True,
        }

    def record_reflection(
        self,
        agent_id: str,
        memory_stream,
        reflection_content: str,
        round_number: int,
        reflection_type: str = "reflection",
    ):
        """Store the reflection back into the memory stream."""
        memory_stream.add_memory(
            content=reflection_content,
            memory_type=reflection_type,
            importance=8,  # Reflections are high-importance
            source="self_reflection",
            round_number=round_number,
        )
        self.last_reflection_round[agent_id] = round_number

    def record_insight(
        self,
        agent_id: str,
        memory_stream,
        insight_content: str,
        round_number: int,
    ):
        """Store a higher-level insight into the memory stream."""
        memory_stream.add_memory(
            content=insight_content,
            memory_type="insight",
            importance=9,  # Insights are very high importance
            source="synthesis",
            round_number=round_number,
        )
